
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.martinmeer: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.datasource.DataSourceTransactionManager: trace
    root: info
    org.springframework.jdbc.core: trace
server:
  port: 8080
