spring:

  datasource:

    url: jdbc:postgresql://176.108.248.118:5432/otk?ssl=false
    username: otkreader
    password: victoria
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.martinmeer: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.datasource.DataSourceTransactionManager: trace
    root: info
    org.springframework.jdbc.core: trace
