server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://176.108.248.118:5432/otk
    username: otkreader
    password: victoria
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Используем Flyway для миграций
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        jdbc.lob.non_contextual_creation: true
        jdbc:
          batch_size: 0

logging:
  level:
    root: debug