server:
  port: ${SERVER_PORT}
  api:


spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.martinmeer: ${LOG_LEVEL_APP}
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.datasource.DataSourceTransactionManager: trace
    root: ${LOG_LEVEL_ROOT}
    org.springframework.jdbc.core: trace

