spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    #jndi-name: java:comp/env/jdbc/otk


logging:
  level:
    root: info
    org.springframework.jdbc.core: debug
    org.martinmeer: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.datasource.DataSourceTransactionManager: debug

server:
  error:
    whitelabel:
      enabled: false
