server:
  port: ${SERVER_PORT:8080}
  api:


spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/otk?ssl=false}
    username: ${DATASOURCE_USERNAME:otkreader}
    password: ${DATASOURCE_PASSWORD:victoria}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.martinmeer: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.jdbc.core.JdbcTemplate: trace
    org.springframework.jdbc.datasource.DataSourceTransactionManager: trace
    root: ${LOG_LEVEL_ROOT:INFO}
    org.springframework.jdbc.core: trace

