spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    jndi-name: java:comp/env/jdbc/otk



  # Этот параметр устанавливает уровень логирования для всего приложения на DEBUG.
  # Это полезно для отладки,
  # но в production-среде рекомендуется установить более высокий уровень логирования (например, INFO или WARN).
  # Если возникают проблемы, увеличьте уровень логирования до TRACE

logging:
  level:
    root: info
    org.springframework.jdbc.core: debug