name: CI/CD Pipeline for Java Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: make mkBuild
      - name: Test with Gradle
        run: make mkTest
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build/libs/*.jar
